### ISSUE TITLE
Debugging method

### ISSUE THREAD

**Issue by DaAwesomeP** [jpearman/convex#4]
My code gave me the slow single red robot flash of doom. I know that it's not ConVEX because when I compile with an effectively blank template or any of the examples it works fine. Is there a way to get output debugging information when running crashing code? Is there an ARM simulator? The current solution is to comment everything and then slowly uncomment blocks, reflash, test, repeat. It's slow going.

**Comment by jpearman** [comment]
You are crashing the user processor, this can happen for many reasons but the most common is stack overflow.  I'm not familiar with any ARM simulators and I doubt that would help you much anyway (due to ConVEX needing specific hardware features).  Try and simplify the code, don't allocate any large arrays as local variables (or change the stack size for that task), if you cannot figure it out then email me the code (my email is in ConVEX source code).

**Comment by DaAwesomeP** [comment]
Well, I solved the problem. I was trying to run a method on something that didn't exist. Debugging 70's style is very fun indeed.
